### ISSUE TITLE
dom/attr: $focused should wait for inserted if element is detached.

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-util#263] opened 2017-05-04 16:01 UTC
https://jsbin.com/mitikugaqi/edit?html,js,console,output

If `$focused` is set to true on an input before its parent frag is inserted to the DOM (i.e. on hydration & initial bindings resolution of a stache), `queueTask()` may not wait long enough for insertion, and `.focus()` on an element not in the DOM is a no-op.

Much like the handler for `$value`, `$focused` should add an "inserted" event listener if an element is not currently on the DOM, to resolve focus after the fragment is added to the DOM.

**Comment by justinbmeyer** [comment] 2017-05-04 16:17
is this a duplicate of: https://github.com/canjs/can-stache-bindings/issues/196 ?

**Comment by justinbmeyer** [comment] 2017-05-04 16:18
@bmomberger-bitovi sounds like a good solution.

**Comment by bmomberger-bitovi** [comment] 2017-05-04 16:21
Yes, it's the same issue, but the problem comes from can-util & not can-stache-bindings, so that one is really a duplicate of this one.

**Closed as completed** 2017-05-04 21:34 UTC
